### ISSUE TITLE
HTML in statement boxes

### ISSUE THREAD

**Issue by rrrebecka** [ChicagoVeg/ChicagoVegSite#10]
There is no urgent need for this if it cannot be done easily.  The statement boxes can remain static text.  The text and titles will need to be changed accordingly though.  

Let me know either way and we can assign this back to Vadim to choose what titles/text will be placed there.  The titles as they currently are now would require HTML in order to include relevant content.

**Comment by zoldello** [comment]
@rrrebecka What is the problem exactly?

**Comment by rrrebecka** [comment]
Nothing major.  Are you okay with the content that's currently in the statement boxes as it is now?  If so, then no worries.  It can be left as is.
