### ISSUE TITLE
Update mobile css stylesheet

### ISSUE THREAD

**Issue by rrrebecka** [ChicagoVeg/ChicagoVegSite#11]
Tidy up CSS for mobile version.

**Comment by rrrebecka** [comment]
Phil, I touched up the statement boxes and right-side images.  Passing this back to you for the nav menu. Not sure what's happening with that.

**Comment by zoldello** [comment]
@rrrebecka What is wrong with the nav?

**Comment by zoldello** [comment]
@rrrebecka Still need information on whats wrong with the nav

**Comment by rrrebecka** [comment]
Updated
