### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by vadim424** [ChicagoVeg/ChicagoVegSite#22]
Make sure the main text is like in production

**Comment by vadim424** [comment]
Did you actually copy and paste?

**Comment by zoldello** [comment]
What text do you see after a hard refresh?

**Comment by vadim424** [comment]
I am sure the same as you do. I see it's not exact what we have on current home page and did not have time to go through every word so I asked you if you copy and paste the entire paragraph or was updating single words. Did you?

**Comment by zoldello** [comment]
As far as I remember and what I see now, I did.  I cut and pasted and
paragraph.

As per copying, I cannot just cut and paste text. There is css styles and
html tags I also need to take into account.

**Comment by vadim424** [comment]
If you did copy and paste the entire paragraph than we don't need to worry about proofreading and need just add period in the end.
Notepad works fine for the pasting text to avoid any formatting issue. Otherwise, yes - you need to be concerned about it.
