### ISSUE TITLE
Add News page (under About Us)

### ISSUE THREAD

**Issue by zoldello** [ChicagoVeg/ChicagoVegSite#23]
Add News page (under About Us). The text can is an api that can be found in:

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="-1"/>
<meta http-equiv="Content-Language" content="en-us"/>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252"/>
<meta name="description" content="ChicagoVeg - Community for Chicago area vegetarians, vegans, raw foodists, or any veg-curious and their friends"/>
<meta name="keywords" content="ChicagoVeg, Chicago Veg, Chicago, Veg, Veggie, Vegetarian, Vegan, Raw Food, Animal Lover, Conscious Living, Save Planet, Solve Environmental Issues, Chicagoland, Chicago area, Chicago suburbs, Vegs, Veggies, Vegetarians, Vegans, Raw Foodists, Animal Welfare, Personal Health, Alternative Healing, Harmony in Life, Community, organic, IL, illinois, people who care"/>
<title>ChicagoVeg ~ News</title>
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="icon" href="favicon.ico" type="image/ico" />
<link rel="stylesheet" type="text/css" href="css/chicagoveg.css" />

<script type="text/javascript" src="http://www.google.com/jsapi?key=ABQIAAAAiUs4aLzQe__jPf-Q6pjQqhQwxYy555uNKeSJP-mFUr2dT6el1hSXYzQV4FH6YZSAtvELcexaTjlpUA"></script>

<script type="text/javascript">
google.load("feeds", "1") //Load Google Ajax Feed API (version 1)
</script>

<script type='text/javascript' src='http://www.feedzilla.com/tools/swfobject.js'></script>

<script type='text/javascript'>var flashvars = {id:'undefined',code:'Flash',c:'nw',scroll:'v',prov:'news',cat:'Science',cat2:'Animals',width:'148',height:'350',num_articles:'10',show_summaries:'yes',show_sources:'Yes',show_dates:'Yes',title:'World Animal News',title_size:'12pt',title_bold:'Yes',keywords:'',url:'Enter the full URL of the feed',headers_size:'12pt',font_size:'10pt',font_family:'Arial',text_alignment:'Justify',space:'Yes',titlecolor:'#000000',fcolor:'#006600',desccolor:'#000000',sourcecolor:'#79B722',datecolor:'#999999',bgcolor:'#EFEADC',ref:document.location.href};var params = {scale:'noscale',salign:'lt',bgcolor:'#EFEADC'};var attributes = {};swfobject.embedSWF('http://www.feedzilla.com/tools/news-widget.swf', 'Feedzilla_news_container', '148', '350', '9.0.0','',flashvars, params, attributes);</script>

</head>

<body background="images/green_bg.jpg">
<center>

<table background="images/green_bg.jpg" border="0" id="Table0" width="700" cellpadding="" cellspacing="0">
<tr><td valign="bottom" rowspan="2"><img id="Left" src="images/left.jpg" alt="" title="" width="107" height="399" /> </td>
<td >
    <br /><table border="1" id="Table1" bgcolor="#99FF33" width="100%" style="border-collapse: collapse">
        <tr>
            <th>
            <font size="5" color="#006600">ChicagoVeg&nbsp;</font><br/>
            <font size="1">For Earth ~ For Animals ~ For You</font></th>
        </tr>
    </table>

```
<br />
<table border="1" id="Table2" bgcolor="#99FF33" width="100%" style="border-collapse: collapse">
    <tr>
        <th style="height: 14px"><font face="Arial" size="1">
        | <a href="index.htm"><img src="images\h_icon.jpg" align="top" alt="Home" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/">HOME</a>
        | <a href="mission.htm"><img src="images\m_icon.jpg" align="top" alt="Mission" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/mission.htm">MISSION</a> 
        | <a href="news.htm"><img src="images\n_icon.jpg" align="top" alt="News" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/news.htm">NEWS</a> 
        | <a href="resources.htm"><img src="images\n_icon.jpg" align="top" alt="Resources" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/resources.htm">RESOURCES</a> 
        | <a href="donate.htm"><img src="images\m_icon.jpg" align="top" alt="Donate" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/donate.htm">DONATE</a>
        | <a href="contact.htm"><img src="images\c_icon.jpg" align="top" alt="Contact Us" border="0" /></a> 
        <a href="http://www.ChicagoVeg.com/contact.htm">CONTACT US</a> 
        | <script type="text/javascript" src="http://w.sharethis.com/button/sharethis.js#publisher=62e3d646-f403-4240-8cde-c17dd87d58d8&amp;type=website&amp;buttonText=SHARE"></script>
        |
        </font></th>
    </tr>
</table>
```

<br />

<table border="1" width="100%" id="Table3" style="border-collapse: collapse" bgcolor="#99FF33" cellpadding="0" cellspacing="1">
        <tr>
            <td>
            <table border="0" width="100%" id="Table4" style="border-collapse: collapse" bgcolor="#99FF33" cellpadding="1" cellspacing="1">
            <tr>
                <td>
                <div id="feeddiv" style="text-align: left"></div>
                <div id="feeddiv2" style="text-align: left"></div>

                <script type="text/javascript">

                var feedcontainer=document.getElementById("feeddiv")
                var feedurl="http://www.chicagoveg.org/rss/g/new"
                // var feedurl="http://www.meetup.com/ChicagoVeg/rss/g/new"
                var feedlimit=16
                var rssoutput="<br/><b><center>ChicagoVeg Meetup News and New Members:</b></center><br /><ul>"

                function rssfeedsetup(){
                var feedpointer=new google.feeds.Feed(feedurl) //Google Feed API method
                feedpointer.setNumEntries(feedlimit) //Google Feed API method
                feedpointer.load(displayfeed) //Google Feed API method
                }

                function displayfeed(result){
                if (!result.error){
                var thefeeds=result.feed.entries
                for (var i=0; i<thefeeds.length; i++)
                rssoutput+="<li> " + thefeeds[i].publishedDate.substr(0,16) + ": <a href='" + thefeeds[i].link + "' target='_new'>" + thefeeds[i].title + "</a></li>"
                rssoutput+="</ul>"
                feedcontainer.innerHTML=rssoutput
                }
                else
                alert("Error fetching feeds!")
                }
                
                window.onload=function(){
                rssfeedsetup()
                }
                </script>
                <center>
                Please check <strong><a href="http://www.ChicagoVeg.org" title="ChicagoVeg – Community for Chicago area Vegetarians, Vegans, Raw Foodists">www.ChicagoVeg.org</a></strong> for more info.
                </center>
                </td>
                <td width="152" align="center">
                
                <div align='center' id='Feedzilla_container1' style='text-align:center;width:148px;'><div id='Feedzilla_container2' style='text-align:center;height:350px;width:148px;border:1px solid #cccccc'><div id='Feedzilla_news_container'></div></div></div>
                
                </td>
            </tr>
            </table>

```
        </td>
     </tr>
</table>
```

</td>
<td valign="bottom" rowspan="2" style="width: 114px"><img id="Right" src="images/right.jpg" alt="" title="" width="112" height="400" /><br/><br/></td>
</tr>
<tr>
<td align="left" valign="bottom"><img id="Bottom" src="images/bottom.jpg" alt="" title="" width="529" height="87" /><br/><br/></td></tr></table>
<br/>
</center>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8612807-1");
pageTracker._trackPageview();
} catch(err) {}
</script>

</body>

</html>

**Comment by vadim424** [comment]
Could you add word "New" before word "Member" to the dynamic list?

**Comment by zoldello** [comment]
This should be done now.
