### ISSUE TITLE
Add some images to top level pages (i.e. About Us, Programs)

### ISSUE THREAD

**Issue by zoldello** [ChicagoVeg/ChicagoVegSite#24]

**Comment by zoldello** [comment]
This involves adding images, to make these pages more stylish.

**Comment by vadim424** [comment]
I don't see any image. Do you?
![image](https://cloud.githubusercontent.com/assets/10101875/15456635/bb889380-203b-11e6-9885-2292977b1971.png)

**Comment by zoldello** [comment]
CTL-F5. You should see it then
