### ISSUE TITLE
fix forms

### ISSUE THREAD

**Issue by zoldello** [ChicagoVeg/ChicagoVegSite#27]
I figured out the issue with contact form.
For the future ChicagoVeg contact forms please use the code from chicagoveg/dev/contact/src/php/form.php
It has corrected wording and fixed reply email header.
You can also use only one js folder (instead of two) as I did for the test form: http://www.chicagoveg.com/dev/contact
- Vadim

On Thursday, March 31, 2016 6:33 AM, Phil greenish_green@yahoo.com wrote:

Hi Vadim,
I am quite busy now and will look at ChicagoVeg mid/afternoon on Saturday. The problem with e-mailing a bug rather than creating a ticket is that by Saturday, I would of had forget this e-mail and the bug not get addressed. If I had a ticket tagged as something that needs to be addressed, I would know it needs fixing. 

If you need to write code, great, the more the merrier. The problem with writing code in production directly is that the file may be lost or overwritten if someone moves code from staging to prod; depending on how it's done. For the captcha, what is the exact issue? The captcha is a security-concern, so you got to understand how it works before reproducing it on a different page.  

Sent from my iPhone

On Mar 31, 2016, at 12:18 AM, Vadim @ ChicagoVeg vadim@chicagoveg.com wrote:

Hi Phil -

The subject of the emails sent from http://www.chicagoveg.com/contact.html still says CVPP instead of ChicagoVeg.

Also, I created chicagoveg.com/dev/contact so I could use this form for myself without all unnecessary files. It works but if I try to copy it on another website it give me an issue with the captcha as it verifies the website/domain name. What should I change so I could use the contact form under a different domain name?
- Vadim

On Saturday, February 20, 2016 6:45 PM, "Vadim @ ChicagoVeg" vadim@chicagoveg.com wrote:

Yes, and the subject say "CVPP Contact Form" - What should I believe? :) 
Could you fix it?
- Vadim

On Saturday, February 20, 2016 6:33 PM, Philip Adenekan greenish_green@yahoo.com wrote:

I believe ChicagoVeg. The form say "ChicagoVeg Main site Contact Form"

From: "Vadim @ ChicagoVeg" vadim@chicagoveg.com
To: Philip Adenekan phil@chicagoveg.com 
Sent: Saturday, February 20, 2016 6:20 PM
Subject: Fw: Message from CVPP Contact Form

Is it from CVPP or ChicagoVeg website?

On Saturday, February 20, 2016 6:12 PM, "onewwwus@just59.justhost.com" onewwwus@just59.justhost.com wrote:

ChicagoVeg Main site Contact Form

From: Lindsay Marshall
E-Mail: lmarshalltx@gmail.com
Message:
Hello! 

I hope this finds you well! I'm reaching out, because I’m currently working with LeAnne Campbell, the founder of Global Roots (www.globalroots.net), an organization that fosters vibrant, inclusive and sustainable communities, locally and internationally, through education programs, study tours and workshops.

Global Roots is offering a week-long plant-based health immersion program in the beautiful Dominican Republic from April 23 - 30, 2016 that I thought might be of interest. At the Total Health Experience immersion program, participants have the chance to:
EAT from a delicious whole food, plant based buffet made with locally grown produce and prepared by an all-star chef.
PLAY on the sandy beaches of Playa Dorada, enjoy fun exercise classes at the resort, and explore the rich culture of the Dominican Republic.
COOK with the engaging and inspiring Chef Del Sroufe.
LEARN how to jump start, promote and sustain optimal health from intimate sessions with some of the leading scientific and medical experts, including Dr. T. Colin Campbell, Dr. Caldwell Esselstyn, Dr. Kathryn Hayward, and Dr. Bruce Monger.

This is the second Total Health Experience, and attendees at the 2015 loved the intimacy of the conference, saying they loved the opportunity to connect directly with others living plant-based and speak directly with top names in the field. You can find more information about program schedule, pricing (early bird rates end March 1), and FAQs at the Global Roots website, www.globalroots.net.

I thought this might be something members of the Vegetarian Society of Richmond might be interested in. If so, we'd love the help spreading the word through your social media. I can also provide some postcards if you have opportunity for placement of literature at your events. I'd love to talk about some other partnership opportunities, as well, if you're interested.

Thanks,
Lindsay
## 

Lindsay Marshall
lmarshalltx@gmail.com
940-594-5758

Time for a break.

**Comment by vadim424** [comment]
Just tried and got this message
![image](https://cloud.githubusercontent.com/assets/10101875/15456614/5cbcea04-203b-11e6-9f1a-fecc78714a5b.png)

**Comment by vadim424** [comment]
Just tried and still doesn't work. Here is the message:
![image](https://cloud.githubusercontent.com/assets/10101875/15458294/74900900-205d-11e6-824a-cb88108780f5.png)
