### ISSUE TITLE
Update Carousel with more captions

### ISSUE THREAD

**Issue by zoldello** [ChicagoVeg/ChicagoVegSite#29]
The carousel looks very good. Let's improve it:
1. Add some captures in the left button corner of each image so people now where it took.
-  Chicago Vegan Mania
-  Veggie Fest in Lisle
-  Quesadilla La Reyna Del Sur
-  Purple Sprouts Cafe
-  Alice and Friends Vegan Kitchen

**Comment by rrrebecka** [comment]
This update is complete and ready for review on Staging.
