### ISSUE TITLE
Change photos and add caption

### ISSUE THREAD

**Issue by zoldello** [ChicagoVeg/ChicagoVegSite#30]
The carousel looks very good. Let's improve it in:

 Let's replace one of the three "food" photos with a "people" attached photo taken last weekend (I included the original photo too). We also need to add this capture: "Montrose Beach Potluck & Volleyball" some place on the left button portion of the image as we do for other images. It's up to you which food photo to replace. Having more than five images might be too much to display and effecting speed of the loading the home page.

**Comment by zoldello** [comment]
I think 5 phots are okay but that should be the limit. It should not have a negative impact on performance.

**Comment by rrrebecka** [comment]
Completed.
