### ISSUE TITLE
Animate home slider

### ISSUE THREAD

**Issue by rrrebecka** [ChicagoVeg/ChicagoVegSite#6]
Please add auto loop to home page slider with subtle fade

Story/Description:  When user enters the website to the home page, the slider will automatically loop. Each slide in the slider will remain for a duration of about 4000 milliseconds. The fade transition will last for about 100 milliseconds.  These numbers are a guestimate.  Please adjust to your liking. :-)

No priority

**Comment by zoldello** [comment]
@rrrebecka: I pushed this off to version 2. Let me know if you have a concern.
